default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: awahids
  password:
  host: localhost

development:
  <<: *default
  database: realtime_chat_dev

test:
  <<: *default
  database: realtime_chat_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
